<nav id="menu">
			<!-- each menu item contains a relevant glyph icon from Bootstrap: uses <span> tags, as recommended by the Bootstrap documentation -->
			<a href="index.php"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</a>
			<a href="topic1.php"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> History</a>
			<a href="topic2.php"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span> What are cookies?</a>
			<a href="topic3.php"><span class="glyphicon glyphicon-globe" aria-hidden="true"></span> Usage</a>
			<a href="topic4.php"><span class="glyphicon glyphicon-transfer" aria-hidden="true"></span> Alternatives</a>
			<a href="quiz.php"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Quiz</a>
			<a href="enhancements.php"><span class="glyphicon glyphicon-education" aria-hidden="true"></span> HTML/CSS Enhancements</a>
			<a href="enhancements2.php"><span class="glyphicon glyphicon-hdd" aria-hidden="true"></span> PHP Enhancements</a>
			<a href="manage.php"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span> Manage</a>
		</nav>